const ArticleActionTypes = {
    ARTICLES_REQUEST: "ARTICLES_REQUEST",
    ARTICLES_FIND_RESPONSE: "ARTICLES_FIND_RESPONSE",
    ARTICLES_FIND_BY_ID_RESPONSE: "ARTICLES_FIND_BY_ID_RESPONSE",
    ARTICLES_SAVE: "ARTICLES_SAVE",
    ARTICLES_UPDATE: "ARTICLES_UPDATE",
    ARTICLES_DELETE: "ARTICLES_DELETE",
    ARTICLES_ERROR: "ARTICLES_ERROR",
};

export default ArticleActionTypes;
